# Generated by Django 4.1 on 2022-08-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nome',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
    ]
